### ISSUE TITLE
Improve update functionality. 

### ISSUE THREAD

**Issue by MonteChristo46** [MonteChristo46/RapidProcessParser#15]
1. Der Nutzer sollte sehen, wieviele Dateien er ausgewählt hat und nach dem Submit sollte auf jeden Fall eine Meldung kommen. 

2. Nicht XML Dateien sollten auf jeden Fall abgefangen werden, oder eine Fehlermeldung generieren.

**Comment by RichardHorn** [comment]
Nur die anzahl der Dateien muss noch ausgegeben werden

**Comment by RichardHorn** [comment]
Anzahl wird Angezeigt und eine Fehlermeldung für "Nicht-XML" Dateien erscheint.
