### ISSUE TITLE
Upload Folder has to be delltet first. 

### ISSUE THREAD

**Issue by MonteChristo46** [MonteChristo46/RapidProcessParser#18]

**Comment by RichardHorn** [comment]
Upload folder wird gelöscht ... Problem: Handling der Unterordner, falls welche vorhanden sind. 
Im Moment ist implementiert, dass er rekursiv durchgeht und alle Dateien im Unterordner löscht. Wenn er das gemacht hat löscht er den Unterordner. Auf Windows wahrscheinlich kein Problem, auf Mac wird allerdings immer eine neue Permission benötigt wenn ein neuer Unterordner da ist ..
